<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MSTest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../testcases/parser/**/*.odl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>testcases\parser\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </None>
    <None Include="../../testcases/parser/**/*.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>testcases\parser\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenDraft.Lang\OpenDraft.Lang.csproj" />
    <ProjectReference Include="..\OpenDraft.Lang.Tools\OpenDraft.Lang.Tools.csproj" />
  </ItemGroup>

</Project>
