name: java-pr

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Configure CMake
        run: cmake -S java -B java/build

      - name: Checkstyle (Sun Style)
        run: cmake --build java/build --target checkstyle

      - name: Build
        run: cmake --build java/build --config Release

      - name: Run Unit Tests
        run: cmake --build java/build --target unit-tests
