name: pr

on:
  pull_request:
    branches:
      - main

jobs:
  cpp-pr:
    uses: ./.github/workflows/cpp-pr.yml

  dotnet-pr:
    uses: ./.github/workflows/dotnet-pr.yml

  java-pr:
    uses: ./.github/workflows/java-pr.yml
